name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull images
        run: "${GITHUB_WORKSPACE}/.github/docker-hub-pull-all.sh"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      -
        name: Keep scheduled workflows alive
        uses: gautamkrishnar/keepalive-workflow@master
        with:
          committer_username: keepalive-bot
          committer_email: keepalive-bot@keepalive-bot
          commit_message: Automated commit by Keepalive Workflow to keep the repository active
          time_elapsed: 30
